import { TopicConfig } from '@/types';

export const jungleConfig: TopicConfig = {
  id: 'jungle',
  title: "Let's Go to the Jungle",
  icon: '🌴',
  color: 'bg-success text-white',
  heroImage: '/images/jungle/animals/panorama-yesno.png',
  vocabulary: ['bee', 'tiger', 'frog', 'lizard', 'monkey', 'spider', 'crocodile', 'elephant', 'rabbit', 'snake'],
  sentences: [
    'There are ___ ___ in the jungle.',
    'I can see a ___ in the jungle.',
  ],
  games: [
    {
      id: 'jungle-honey-bridge',
      type: 'honey-bridge',
      title: 'Honey Bridge Builder',
      description: 'Help Milo cross! Tap letters in order to build the word bridge.',
      difficulty: 1,
      hideFromTopicList: true,
    },
    {
      id: 'jungle-shadow-match',
      type: 'shadow-match',
      title: "Tiger's Shadow Match",
      description: 'Listen in the dark cave and tap the animal shadow Milo describes.',
      difficulty: 1,
      dependsOn: ['jungle-honey-bridge'],
      hideFromTopicList: true,
    },
    {
      id: 'jungle-lily-pad-count',
      type: 'lily-pad-count',
      title: 'Lily Pad Count',
      description: 'Count the frogs and crocs so Milo can hop across the swamp!',
      difficulty: 2,
      dependsOn: ['jungle-shadow-match'],
      hideFromTopicList: true,
    },
    {
      id: 'jungle-fruit-catch',
      type: 'fruit-catch',
      title: 'Fruit Catch',
      description: 'Catch only the fruit Milo names — quick eyes in the monkey tree!',
      difficulty: 2,
      dependsOn: ['jungle-lily-pad-count'],
      hideFromTopicList: true,
    },
    {
      id: 'jungle-checkpoint',
      type: 'final-checkpoint',
      title: 'Topic Check',
      description: 'Final review: listening, reading, writing, and a short speaking task!',
      difficulty: 3,
      dependsOn: ['jungle-fruit-catch'],
    },
    {
      id: 'jungle-vocab',
      type: 'vocab-intro',
      title: 'New Words',
      description: 'Listen, read the word, and look at the picture!',
      difficulty: 1,
      dependsOn: ['jungle-checkpoint'],
    },
    {
      id: 'jungle-listen-pick',
      type: 'listen-pick',
      title: 'Listen & Pick',
      description: 'Read the story, tap to listen, then pick the right picture!',
      difficulty: 1,
      dependsOn: ['jungle-checkpoint'],
    },
    {
      id: 'jungle-spelling',
      type: 'spelling',
      title: 'Spelling Master',
      description: 'Find the extra letter hiding in the word!',
      difficulty: 1,
      dependsOn: ['jungle-checkpoint'],
    },
    {
      id: 'jungle-reading',
      type: 'reading-quiz',
      title: 'Look & Read',
      description: 'Look at the scene and tick the correct sentence!',
      difficulty: 2,
      dependsOn: ['jungle-checkpoint'],
    },
    {
      id: 'jungle-count',
      type: 'count-complete',
      title: 'Count & Complete',
      description: 'Count the animals in the jungle and fill in the sentence!',
      difficulty: 3,
      dependsOn: ['jungle-checkpoint'],
    },
    {
      id: 'jungle-scene',
      type: 'scene-reading',
      title: 'Who Lives Here?',
      description: 'Look at the jungle and write yes or no!',
      difficulty: 3,
      dependsOn: ['jungle-checkpoint'],
    },
    {
      id: 'jungle-speaking',
      type: 'speaking-present',
      title: 'Speaking Presentation',
      description: 'Look at the picture and tell your own jungle story!',
      difficulty: 3,
      dependsOn: ['jungle-count', 'jungle-scene'],
    },
  ],
};
